services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app_network
    depends_on:
      - db
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d"
      COMPOSER_ALLOW_SUPERUSER: 1
    command: php -S 0.0.0.0:9000 -t public

  db:
    image: mysql:8.0
    container_name: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - app_network

  seed:
    image: php:8.2-cli
    container_name: db_seeder
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/config
    depends_on:
      - db
    networks:
      - app_network
    entrypoint: ["php", "seed.php"]

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
